# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 884)
        MainWindow.setStyleSheet("/*\n"
"Material Dark Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Inspired on https://github.com/jxfwinter/qt-material-stylesheet\n"
"Company: GTRONICK\n"
"Last updated: 04/12/2018, 15:00.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/MaterialDark.qss\n"
"*/\n"
"QMainWindow, QWidget{\n"
"    background-color:#1e1d23;\n"
"}\n"
"\n"
"QDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QColorDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTextEdit {\n"
"    background-color:#1e1d23;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPlainTextEdit {\n"
"    selection-background-color:#007b50;\n"
"    background-color:#1e1d23;\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"                                      stop: 0 #dadbde, stop:  1 rgb(80, 195, 26));\n"
"border: 1px solid; \n"
"border-radius:70%; \n"
"color: #99615f;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: inset;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: #ffffff;\n"
"    border-right-color: #ffffff;\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #ffffff;\n"
"    border-left-width: 1px;\n"
"    border-right-width: 1px;\n"
"    border-top-width: 1px;\n"
"    border-bottom-width: 1px;\n"
"\n"
"    border-style: solid;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"                                      stop: 0 #dadbde, stop:  1 rgb(68, 162, 21));\n"
"    padding-bottom: 2px;\n"
"     color: #FFFFFF;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    \n"
"    border-top-color: #ffffff;\n"
"    border-right-color: #ffffff;\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #ffffff;\n"
"    border-left-width: 3px;\n"
"    border-right-width: 3px;\n"
"    border-top-width: 3px;\n"
"    border-bottom-width: 3px;\n"
"    border-style: solid;\n"
"     color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"                                      stop: 0 #dadbde, stop:  1 rgb(68, 162, 21));}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"n\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #808086;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: #a9b7c6;\n"
"    background:#1e1d23;\n"
"    selection-background-color:#007b50;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"QLabel {\n"
"    color: #a9b7c6;\n"
"}\n"
"QLCDNumber {\n"
"    color: #37e6b4;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:#1e1d23;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #04b97f;\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #a9b7c6;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"      background: #1e1d23;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background:#1e1d23;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: #04b97f;\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #FFFFFF;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu{\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#1e1d23;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:#1e1d23;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-radius: 20%;\n"
"    border-top-color: white;\n"
"    border-right-color: white;\n"
"    border-left-color: white;\n"
"    border-bottom-color: white;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding: 3px;\n"
"    margin-left:3px;\n"
"    width: 70px;\n"
"    height: 25px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-left: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QRadioButton {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QComboBox {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #1e1d23;\n"
"    color: #a9b7c6;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"    selection-color: #FFFFFF;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QFontComboBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 14px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #04b97f;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.powerbuttonlayout = QtWidgets.QVBoxLayout()
        self.powerbuttonlayout.setContentsMargins(-1, 35, -1, 150)
        self.powerbuttonlayout.setObjectName("powerbuttonlayout")
        self.statuslabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statuslabel.sizePolicy().hasHeightForWidth())
        self.statuslabel.setSizePolicy(sizePolicy)
        self.statuslabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.statuslabel.setFont(font)
        self.statuslabel.setStyleSheet("color: white; background-color:  #c3777a;")
        self.statuslabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.statuslabel.setObjectName("statuslabel")
        self.powerbuttonlayout.addWidget(self.statuslabel)
        self.titlelabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titlelabel.sizePolicy().hasHeightForWidth())
        self.titlelabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.titlelabel.setFont(font)
        self.titlelabel.setStyleSheet("")
        self.titlelabel.setWordWrap(True)
        self.titlelabel.setObjectName("titlelabel")
        self.powerbuttonlayout.addWidget(self.titlelabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.powerbuttonlayout.addItem(spacerItem)
        self.hvsystemtoggleframe = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvsystemtoggleframe.sizePolicy().hasHeightForWidth())
        self.hvsystemtoggleframe.setSizePolicy(sizePolicy)
        self.hvsystemtoggleframe.setObjectName("hvsystemtoggleframe")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.hvsystemtoggleframe)
        self.verticalLayout_3.setContentsMargins(-1, 250, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hvsystemtogglelabel = QtWidgets.QLabel(self.hvsystemtoggleframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.hvsystemtogglelabel.sizePolicy().hasHeightForWidth())
        self.hvsystemtogglelabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.hvsystemtogglelabel.setFont(font)
        self.hvsystemtogglelabel.setStyleSheet("")
        self.hvsystemtogglelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hvsystemtogglelabel.setWordWrap(True)
        self.hvsystemtogglelabel.setObjectName("hvsystemtogglelabel")
        self.verticalLayout_3.addWidget(self.hvsystemtogglelabel)
        self.hvsystembutton = QtWidgets.QPushButton(self.hvsystemtoggleframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvsystembutton.sizePolicy().hasHeightForWidth())
        self.hvsystembutton.setSizePolicy(sizePolicy)
        self.hvsystembutton.setMinimumSize(QtCore.QSize(0, 154))
        self.hvsystembutton.setMaximumSize(QtCore.QSize(16777215, 187))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.hvsystembutton.setFont(font)
        self.hvsystembutton.setStyleSheet("color: white; background-color: rgb(170, 170, 127);\n"
"")
        self.hvsystembutton.setCheckable(True)
        self.hvsystembutton.setChecked(False)
        self.hvsystembutton.setObjectName("hvsystembutton")
        self.verticalLayout_3.addWidget(self.hvsystembutton)
        self.hvcheckbox = QtWidgets.QCheckBox(self.hvsystemtoggleframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvcheckbox.sizePolicy().hasHeightForWidth())
        self.hvcheckbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hvcheckbox.setFont(font)
        self.hvcheckbox.setIconSize(QtCore.QSize(16, 16))
        self.hvcheckbox.setObjectName("hvcheckbox")
        self.verticalLayout_3.addWidget(self.hvcheckbox)
        self.powerbuttonlayout.addWidget(self.hvsystemtoggleframe)
        self.horizontalLayout.addLayout(self.powerbuttonlayout)
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabs.setFont(font)
        self.tabs.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setIconSize(QtCore.QSize(16, 16))
        self.tabs.setElideMode(QtCore.Qt.ElideNone)
        self.tabs.setUsesScrollButtons(True)
        self.tabs.setDocumentMode(False)
        self.tabs.setTabsClosable(False)
        self.tabs.setMovable(False)
        self.tabs.setObjectName("tabs")
        self.tab_summary = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_summary.sizePolicy().hasHeightForWidth())
        self.tab_summary.setSizePolicy(sizePolicy)
        self.tab_summary.setObjectName("tab_summary")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_summary)
        self.gridLayout.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.summaryvoltagelinegraph = VLinePlot(self.tab_summary)
        self.summaryvoltagelinegraph.setObjectName("summaryvoltagelinegraph")
        self.gridLayout.addWidget(self.summaryvoltagelinegraph, 0, 2, 1, 1)
        self.summaryvoltagebargraph = VBarPlot(self.tab_summary)
        self.summaryvoltagebargraph.setObjectName("summaryvoltagebargraph")
        self.gridLayout.addWidget(self.summaryvoltagebargraph, 0, 4, 1, 1)
        self.summarytemplinegraph = TLinePlot(self.tab_summary)
        self.summarytemplinegraph.setObjectName("summarytemplinegraph")
        self.gridLayout.addWidget(self.summarytemplinegraph, 1, 2, 1, 1)
        self.summarytempbargraph = TBarPlot(self.tab_summary)
        self.summarytempbargraph.setObjectName("summarytempbargraph")
        self.gridLayout.addWidget(self.summarytempbargraph, 1, 4, 1, 1)
        self.tabs.addTab(self.tab_summary, "")
        self.tab_voltage = QtWidgets.QWidget()
        self.tab_voltage.setObjectName("tab_voltage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_voltage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.voltagerecordbutton = QtWidgets.QPushButton(self.tab_voltage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltagerecordbutton.sizePolicy().hasHeightForWidth())
        self.voltagerecordbutton.setSizePolicy(sizePolicy)
        self.voltagerecordbutton.setMinimumSize(QtCore.QSize(61, 61))
        self.voltagerecordbutton.setMaximumSize(QtCore.QSize(61, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.voltagerecordbutton.setFont(font)
        self.voltagerecordbutton.setStyleSheet("color: white; background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #dadbde, stop:  1 #de1641);")
        self.voltagerecordbutton.setCheckable(True)
        self.voltagerecordbutton.setObjectName("voltagerecordbutton")
        self.verticalLayout_4.addWidget(self.voltagerecordbutton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.voltagegraph = VLinePlot(self.tab_voltage)
        self.voltagegraph.setObjectName("voltagegraph")
        self.horizontalLayout_2.addWidget(self.voltagegraph)
        self.tabs.addTab(self.tab_voltage, "")
        self.tab_temperature = QtWidgets.QWidget()
        self.tab_temperature.setObjectName("tab_temperature")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_temperature)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.temprecordbutton = QtWidgets.QPushButton(self.tab_temperature)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temprecordbutton.sizePolicy().hasHeightForWidth())
        self.temprecordbutton.setSizePolicy(sizePolicy)
        self.temprecordbutton.setMinimumSize(QtCore.QSize(61, 61))
        self.temprecordbutton.setMaximumSize(QtCore.QSize(61, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.temprecordbutton.setFont(font)
        self.temprecordbutton.setStyleSheet("color: white; background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #dadbde, stop:  1 #de1641);\n"
"")
        self.temprecordbutton.setCheckable(True)
        self.temprecordbutton.setObjectName("temprecordbutton")
        self.verticalLayout_2.addWidget(self.temprecordbutton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tempgraph = TLinePlot(self.tab_temperature)
        self.tempgraph.setObjectName("tempgraph")
        self.horizontalLayout_3.addWidget(self.tempgraph)
        self.tabs.addTab(self.tab_temperature, "")
        self.tab_current = QtWidgets.QWidget()
        self.tab_current.setObjectName("tab_current")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_current)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.currentrecordbutton = QtWidgets.QPushButton(self.tab_current)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentrecordbutton.sizePolicy().hasHeightForWidth())
        self.currentrecordbutton.setSizePolicy(sizePolicy)
        self.currentrecordbutton.setMinimumSize(QtCore.QSize(61, 61))
        self.currentrecordbutton.setMaximumSize(QtCore.QSize(61, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.currentrecordbutton.setFont(font)
        self.currentrecordbutton.setStyleSheet("color: white; background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #dadbde, stop:  1 #de1641);")
        self.currentrecordbutton.setCheckable(True)
        self.currentrecordbutton.setObjectName("currentrecordbutton")
        self.verticalLayout.addWidget(self.currentrecordbutton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.currentgraph = CLinePlot(self.tab_current)
        self.currentgraph.setObjectName("currentgraph")
        self.horizontalLayout_4.addWidget(self.currentgraph)
        self.tabs.addTab(self.tab_current, "")
        self.horizontalLayout.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UTHT Power System Testing Interface"))
        self.statuslabel.setText(_translate("MainWindow", "Status: OFF"))
        self.titlelabel.setText(_translate("MainWindow", "Power System Interface"))
        self.hvsystemtogglelabel.setText(_translate("MainWindow", "HV System Toggle"))
        self.hvsystembutton.setText(_translate("MainWindow", "DISENGAGED"))
        self.hvcheckbox.setText(_translate("MainWindow", "Show 288V Battery"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_summary), _translate("MainWindow", "Summary"))
        self.voltagerecordbutton.setText(_translate("MainWindow", "Not\n"
"Recording"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_voltage), _translate("MainWindow", "Voltage"))
        self.temprecordbutton.setText(_translate("MainWindow", "Not\n"
"Recording"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_temperature), _translate("MainWindow", "Temp"))
        self.currentrecordbutton.setText(_translate("MainWindow", "Not\n"
"Recording"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_current), _translate("MainWindow", "Current"))
from plot import CLinePlot, TBarPlot, TLinePlot, VBarPlot, VLinePlot
